---
localhost:
  hostname: james
  groups:
    - ios
  data:
    dns1: 8.8.8.8
khade:
  hostname: greg
  groups:
    - ios
norzel:
  hostname: oscar
  groups: 
    - ios
hazel:
  hostname: rosio
  groups:
    - ios

